title: Eduardo Esteves
logo: /assets/img/profile.jpg
description: With over a decade of experience in proteomics, bioinformatics, and European data infrastructures, I focus on transforming complex datasets into actionable insights. My journey spans academic research, digital health start-ups, and international science policy.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
