title: Eduardo Esteves
logo: /assets/img/profile2.jpg
description: With 5+ years of experience using machine learning models and statistical analysis to develop predictive models, optimise data handling processes and create meaningful visualisations. Proficient in Python and cloud technologies with an interest in data analysis.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
